"use client";

import { createContext, useContext, useSyncExternalStore } from "react";

/**
 * Language Provider & Translation System
 * 
 * This module provides internationalization (i18n) support for the application.
 * It manages language state, provides translation functions, and persists user preferences.
 */

// Type for supported languages
type Language = "en" | "fr" | "es";

// Interface defining the shape of the language context
interface LanguageContextType {
  language: Language;              // Current active language
  toggleLanguage: () => void;      // Function to switch languages
  t: (key: string) => string;      // Translation function
}

/**
 * Translation dictionary
 * Add new translation keys here for both languages
 * Usage: t("key") will return the translated string
 */
const translations = {
  en: {
    welcome: "Welcome to ft_transcendence",
    content: "Your application content goes here.",
    language: "Language",
    hello: "Hello",
    extraInfo: "Extra info",
    signIn: "Sign in",
    signUp: "Sign up",
    username: "Username",
    password: "Password",
    email: "Email",
    confirmPassword: "Confirm Password",
    friendsList: "Friends List",
    playVsBots: "Play vs Bots",
    playVsHumans: "Play vs Humans",
    playVsPlayers: "Player vs Player",
    logout: "Log out",
    profileTitle: "My profile",
    publicProfileTitle: "Public profile",
    profileDetails: "Profile details",
    gamesPlayed: "Games played",
    gamesWon: "Games won",
    profileText: "Profile text",
    profileTextPlaceholder: "Write a short text for your profile...",
    profileTextEmpty: "No profile text yet.",
    saveProfileText: "Save text",
    profileTextSaved: "Profile text saved",
    failedSaveProfileText: "Failed to save profile text",
    profileActions: "Actions",
    profileDangerZone: "Danger zone",
    deleteAccount: "Delete account",
    confirmDeleteAccount: "Are you sure you want to delete your account? This action is irreversible.",
    deletingAccount: "Deleting...",
    failedDeleteAccount: "Failed to delete account",
    settings: "Settings",
    change: "Change",
    changeemailaddress: "Change email address",
    changeusername: "Change username",
    changeprofilepicture: "Change profile picture",
    changepassword: "Change password",
    changeEmail: "Change email",
    changePassword: "Change password",
    changeProfilePicture: "Change profile picture",
    confirmEmail: "Confirm email",
    confirmNewEmail: "Confirm new email",
    confirmNewPassword: "Confirm new password",
    confirmNewUsername: "Confirm new username",
    confirmUsername: "Confirm username",
    currentEmail: "Current email",
    currentPassword: "Current password",
    currentUsername: "Current username",
    emailsDoNotMatch: "Emails do not match",
    enterCurrentPassword: "Enter current password",
    enterNewEmail: "Enter new email",
    enterNewPassword: "Enter new password",
    enterNewUsername: "Enter new username",
    fileTooLarge: "File is too large (max 5MB)",
    imageRequirements: "PNG, JPG, WEBP or GIF, up to 5MB",
    invalidEmail: "Invalid email address",
    invalidFileType: "Invalid file type",
    invalidUsername: "Invalid username",
    key: "Key",
    newEmail: "New email",
    newPassword: "New password",
    newUsername: "New username",
    noFileSelected: "No file selected",
    passwordNeedsNumber: "Password must include at least one number",
    passwordNeedsUppercase: "Password must include at least one uppercase letter",
    passwordRequirements: "At least 8 characters, one uppercase letter and one number",
    passwordTooShort: "Password is too short",
    passwordsDoNotMatch: "Passwords do not match",
    sameEmail: "New email must be different",
    samePassword: "New password must be different",
    sameUsername: "New username must be different",
    selectImage: "Select image",
    userExists: "User already exists",
    usernamesDoNotMatch: "Usernames do not match",
    yourKey: "Your key",
    profilePicture: "Profile Picture",
    rock: "rock",
    paper: "paper",
    scissors: "scissors",
    selected: "Selected",
    botChoice: "Bot's Choice",
    opponentChoice: "Opponent's Choice",
    yourChoice: "Your Choice",
    playAgain: "Play Again",
    scoreTrackingComingSoon: "Score tracking coming soon...",
    you: "You",
    bot: "Bot",
    opponent: "Opponent",
    rockPaperScissors: "Rock Paper Scissors",
    createRoom: "Create a room",
    joinRoom: "Join a room",
    makeYourChoice: "Make your choice",
    enterRoomName: "Enter a room name",
    roomNamePlaceholder: "My Room",
    characters: "characters",
    incorrectCredentials: "Incorrect username or password. Please check your credentials and try again.",
    fillAllFields: "Please fill all fields",
    serverUnavailable: "Unable to connect to server. Please check if backend is running.",
    currentPasswordIncorrect: "Current password is incorrect",
    social: "Social",
    searchFriends: "Search friends",
    activeFriends: "Active friends",
    friendsCountUnit: "friends",
    statusOnline: "online",
    statusChatting: "chatting",
    statusInGame: "in game",
    statusOffline: "offline",
    status: "Status",
    chatTitle: "Chat",
    chatDirectMessages: "Direct Messages",
    chatSearchFriend: "Search a friend",
    chatUnreadSuffix: "unread",
    chatNoFriendFound: "No friend found.",
    chatConversation: "Conversation",
    chatSelectFriend: "Select a friend",
    chatTyping: "Typing...",
    chatConnected: "Connected",
    chatReconnecting: "Reconnecting",
    chatWriteMessage: "Write a message...",
    chatSend: "Send",
    chatSelectFriendToWrite: "Select a friend to start writing messages.",
    chatPickFriendPrompt: "Pick a friend in the left panel to start chatting.",
    chatNoMessagesYet: "No messages yet. Say hi.",
    chatSeen: "Seen",
    chatFailedLoadProfile: "Unable to load your profile",
    chatFailedLoadMessages: "Unable to load messages",
    chatFailedLoadFriends: "Unable to load friends",
    chatFailedInitialize: "Unable to initialize chat",
    chatRealtimeError: "Realtime chat error",
    chatRealtimeParseError: "Unable to parse realtime event",
    chatRealtimeConnectionError: "Realtime connection error",
    chatSelectFriendFirst: "Select a friend first",
    chatConnectionNotReady: "Realtime connection is not ready",
    chatInvalidFriendId: "Invalid friend id",
    chatWsMissingToken: "Missing auth token",
    chatWsInvalidToken: "Invalid auth token",
    chatWsNotRegistered: "Not registered",
    chatWsInvalidToUserId: "Invalid recipient",
    chatWsInvalidWithUserId: "Invalid target user",
    chatWsInvalidMessage: "Invalid message",
    chatWsNotFriends: "Not friends",
    chatWsFailedSaveMessage: "Failed to save message",
    chatWsUnknownMessageType: "Unknown message type",
    chatWsMessageTooLarge: "Message too large",
    chatWsInvalidJson: "Invalid JSON",
    noEloYet: "No ELO yet",
    avatarAltSuffix: "avatar",
    lastSeen: "Last seen",
    inviteToPlay: "Invite to play",
    remove: "Remove",
    noFriendsMatch: "No friends match your search",
    addFriend: "Add friend",
    usernameOrEmail: "Username or ID",
    sending: "Sending...",
    sendRequest: "Send request",
    messageAction: "Message",
    requests: "Requests",
    pending: "pending",
    noPendingRequests: "No pending requests",
    enterUsernameOrId: "Please enter a username or id",
    missingAuthToken: "Missing auth token",
    userNotFound: "User not found",
    failedSendRequest: "Failed to send friend request",
    requestSent: "Friend request sent",
    loadingFriends: "Loading friends...",
    unableLoadFriends: "Unable to load friends",
    loading: "Loading...",
    mutualFriends: "mutual friends",
    accept: "Accept",
    decline: "Decline",
    failedAcceptRequest: "Failed to accept request",
    failedRejectRequest: "Failed to reject request",
    failedRemoveFriend: "Failed to remove friend",
    friendRequestAlreadyExists: "Friend request already exists",
    alreadyFriends: "Already friends",
    cannotAddYourself: "Cannot add yourself",
    friendRequestAcceptedAuto: "Friend request accepted",
    friendNotFound: "Friend not found",
    failedLoadFriendRequests: "Failed to load friend requests",
    failedLoadFriends: "Failed to load friends",
    failedResolveUser: "Unable to resolve this user",
    // Extra Info Page
    aboutThisGame: "About This Game",
    aboutGameDesc: "Welcome to ft_transcendence, a modern online Rock Paper Scissors game platform. Play against AI bots or challenge other players in real-time multiplayer matches.",
    trackScoreDesc: "Track your score, compete with friends, and improve your strategy in this classic game of chance and skill.",
    howToPlay: "How to Play",
    playVsBotsDesc: "Challenge AI opponents and test your skills",
    playVsHumansDesc: "Create or join a room to play with other players",
    scoreTrackingDesc: "Your scores persist throughout your gaming session",
    multipleRoundsDesc: "Play as many rounds as you want",
    accountSettings: "Account Settings",
    manageProfileDesc: "Manage your profile from the Settings page:",
    changeUsername: "Change your username",
    updateEmail: "Update your email address",
    updatePassword: "Change your password",
    updateProfilePic: "Update your profile picture",
    legalPrivacy: "Legal & Privacy",
    reviewPoliciesDesc: "Please review our important policies before using the application:",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    faq: "Frequently Asked Questions",
    isDataSecure: "Is my data secure?",
    isDataSecureAns: "Yes, we use industry-standard encryption to protect your personal data. See our Privacy Policy for details.",
    canPlayOffline: "Can I play offline?",
    canPlayOfflineAns: "This game requires an internet connection to play, as scores and multiplayer features are server-dependent.",
    reportBug: "How do I report a bug?",
    reportBugAns: "If you encounter any issues, please contact support through your account settings.",
    // Privacy Policy Page
    privacyPageTitle: "Privacy Policy",
    lastUpdated: "Last updated:",
    privacyIntro: "ft_transcendence is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our application.",
    privacySection1: "Introduction",
    privacySection2: "Information We Collect",
    privacyCollectDesc: "We may collect information about you in a variety of ways. The information we may collect on the Site includes:",
    privacyPersonalData: "Personal Data: Username, email address, password, profile picture, and account preferences.",
    privacyGameData: "Game Data: Game scores, match history, and gameplay statistics.",
    privacyUsageData: "Usage Data: Information about how you interact with the application, including IP address and device information.",
    privacyCookies: "Cookies: We use cookies to enhance your user experience and track your preferences.",
    privacySection3: "Use of Your Information",
    privacyUseDesc: "Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Site to:",
    privacyUse1: "Create and manage your account",
    privacyUse2: "Process and improve your gaming experience",
    privacyUse3: "Track your game statistics and scores",
    privacyUse4: "Send you notifications about game-related updates",
    privacyUse5: "Respond to your inquiries and provide customer support",
    privacyUse6: "Monitor and analyze usage patterns and trends",
    privacySection4: "Disclosure of Your Information",
    privacyDisclosureDesc: "We do not sell, trade, or rent users' personal identification information to others. We may disclose information when required by law or in good faith belief that such disclosure is necessary to comply with legal obligations.",
    privacySection5: "Security of Your Information",
    privacySecurityDesc: "We use administrative, technical, and physical security measures to protect your personal information. However, no method of transmission over the Internet or electronic storage is completely secure. While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.",
    privacySection6: "Contact Us",
    privacyContactDesc: "If you have questions or comments about this Privacy Policy, please contact us through your account settings or the support section of the application.",
    privacySection7: "Changes to This Privacy Policy",
    privacyChangesDesc: "We reserve the right to modify this privacy policy at any time. Changes and clarifications will take effect immediately upon their posting to the website. If we make material changes to this policy, we will notify you here that it has been updated.",
    // Terms of Service Page
    termsPageTitle: "Terms of Service",
    termsSection1: "Agreement to Terms",
    termsAgreementDesc: "By accessing and using ft_transcendence, you accept and agree to be bound by and comply with these Terms and Conditions. If you do not agree to abide by the above, please do not use this service.",
    termsSection2: "Use License",
    termsLicenseDesc: "Permission is granted to temporarily download one copy of the materials (information or software) on ft_transcendence for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:",
    termsLicense1: "Modify or copy the materials",
    termsLicense2: "Use the materials for any commercial purpose or for any public display",
    termsLicense3: "Attempt to decompile or reverse engineer any software contained on the Application",
    termsLicense4: "Remove any copyright or other proprietary notations from the materials",
    termsLicense5: "Transfer the materials to another person or \"mirror\" the materials on any other server",
    termsLicense6: "Violate any applicable laws or regulations related to access to or use of the Application",
    termsSection3: "Account Registration",
    termsAccountDesc: "When you create an account on ft_transcendence, you agree to provide accurate, current, and complete information. You are responsible for maintaining the confidentiality of your account information and password, and you agree to accept responsibility for all activities that occur under your account.",
    termsSection4: "User Conduct",
    termsConductDesc: "You agree not to engage in any conduct that restricts or inhibits any person's use or enjoyment of the Application, including:",
    termsConduct1: "Harassing or causing distress or inconvenience to any person",
    termsConduct2: "Transmitting obscene or offensive content",
    termsConduct3: "Disrupting the normal flow of dialogue within the Application",
    termsConduct4: "Attempting to gain unauthorized access to the Application or its systems",
    termsConduct5: "Using automated tools to collect data from the Application",
    termsSection5: "Disclaimer of Warranties",
    termsWarrantiesDesc: "The materials on ft_transcendence are provided on an 'as is' basis. ft_transcendence makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.",
    termsSection6: "Limitation of Liability",
    termsLiabilityDesc: "In no event shall ft_transcendence or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on ft_transcendence.",
    termsSection7: "Accuracy of Materials",
    termsAccuracyDesc: "The materials appearing on ft_transcendence could include technical, typographical, or photographic errors. ft_transcendence does not warrant that any of the materials on the Application are accurate, complete, or current.",
    termsSection8: "Modifications",
    termsModificationsDesc: "ft_transcendence may revise these terms of service for the Application at any time without notice. By using this Application, you are agreeing to be bound by the then current version of these terms of service.",
    termsSection9: "Governing Law",
    termsGoverningDesc: "These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction in which ft_transcendence operates, and you irrevocably submit to the exclusive jurisdiction of the courts located in that area.",
    termsSection10: "Contact Information",
    termsContactDesc: "If you have any questions about these Terms of Service, please contact us through the support section of the application.",
    allRightsReserved: "All rights reserved.",
    room: "Room",
    creatingRoom: "Creating room...",
    creatingGame: "Creating game...",
    joiningRoom: "Joining room...",
    roomNotFound: "Room not found",
    roomCreatedWaiting: "Room created. Waiting for opponent...",
    missingRoomCode: "Missing room code",
    connectionNotReady: "Connection not ready",
    gameFinished: "Game finished",
    vs: "VS",
    validate: "Validate"
  },
  fr: {
    welcome: "Bienvenue à ft_transcendence",
    content: "Le contenu de votre application va ici.",
    language: "Langue",
    hello: "Bonjour",
    extraInfo: "Infos supplémentaires",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    email: "Email",
    confirmPassword: "Confirmer le mot de passe",
    friendsList: "Liste d'amis",
    playVsBots: "Jouer vs des bots",
    playVsHumans: "Jouer vs des humains",
    playVsPlayers: "Joueur contre joueur",
    logout: "Se déconnecter",
    profileTitle: "Mon profil",
    publicProfileTitle: "Profil public",
    profileDetails: "Informations du profil",
    gamesPlayed: "Parties jouées",
    gamesWon: "Parties gagnées",
    profileText: "Texte du profil",
    profileTextPlaceholder: "Écris un petit texte pour ton profil...",
    profileTextEmpty: "Pas encore de texte de profil.",
    saveProfileText: "Sauvegarder le texte",
    profileTextSaved: "Texte du profil sauvegardé",
    failedSaveProfileText: "Impossible de sauvegarder le texte du profil",
    profileActions: "Actions",
    profileDangerZone: "Zone de danger",
    deleteAccount: "Supprimer le compte",
    confirmDeleteAccount: "Voulez-vous vraiment supprimer votre compte ? Cette action est irreversible.",
    deletingAccount: "Suppression...",
    failedDeleteAccount: "Echec de la suppression du compte",
    settings: "Paramètres",
    change: "Modifier",
    changeemailaddress: "Changer l'adresse e-mail",
    changeusername: "Changer le nom d'utilisateur",
    changeprofilepicture: "Changer la photo de profil",
    changepassword: "Changer le mot de passe",
    changeEmail: "Changer l'email",
    changePassword: "Changer le mot de passe",
    changeProfilePicture: "Changer la photo de profil",
    confirmEmail: "Confirmez l'email",
    confirmNewEmail: "Confirmez le nouvel email",
    confirmNewPassword: "Confirmez le nouveau mot de passe",
    confirmNewUsername: "Confirmez le nouveau nom d'utilisateur",
    confirmUsername: "Confirmez le nom d'utilisateur",
    currentEmail: "Email actuel",
    currentPassword: "Mot de passe actuel",
    currentUsername: "Nom d'utilisateur actuel",
    emailsDoNotMatch: "Les emails ne correspondent pas",
    enterCurrentPassword: "Entrez le mot de passe actuel",
    enterNewEmail: "Entrez le nouvel email",
    enterNewPassword: "Entrez le nouveau mot de passe",
    enterNewUsername: "Entrez le nouveau nom d'utilisateur",
    fileTooLarge: "Fichier trop volumineux (max 5 Mo)",
    imageRequirements: "PNG, JPG, WEBP ou GIF, 5 Mo max",
    invalidEmail: "Email invalide",
    invalidFileType: "Type de fichier invalide",
    invalidUsername: "Nom d'utilisateur invalide",
    key: "Cle",
    newEmail: "Nouvel email",
    newPassword: "Nouveau mot de passe",
    newUsername: "Nouveau nom d'utilisateur",
    noFileSelected: "Aucun fichier selectionne",
    passwordNeedsNumber: "Le mot de passe doit contenir au moins un chiffre",
    passwordNeedsUppercase: "Le mot de passe doit contenir au moins une majuscule",
    passwordRequirements: "Au moins 8 caracteres, une majuscule et un chiffre",
    passwordTooShort: "Mot de passe trop court",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
    sameEmail: "Le nouvel email doit etre different",
    samePassword: "Le nouveau mot de passe doit etre different",
    sameUsername: "Le nouveau nom d'utilisateur doit etre different",
    selectImage: "Selectionner une image",
    userExists: "Utilisateur deja existant",
    usernamesDoNotMatch: "Les noms d'utilisateur ne correspondent pas",
    yourKey: "Votre cle",
    profilePicture: "Photo de profil",
    rock: "pierre",
    paper: "papier",
    scissors: "ciseaux",
    selected: "Sélectionné",
    botChoice: "Choix du bot",
    opponentChoice: "Choix de l'adversaire",
    yourChoice: "Votre choix",
    playAgain: "Rejouer",
    scoreTrackingComingSoon: "Suivi du score bientôt disponible...",
    you: "Vous",
    bot: "Bot",
    opponent: "Adversaire",
    rockPaperScissors: "Pierre Papier Ciseaux",
    createRoom: "Créer une salle",
    joinRoom: "Rejoindre une salle",
    makeYourChoice: "Faites votre choix",
    enterRoomName: "Entrez un nom de salle",
    roomNamePlaceholder: "Ma Salle",
    characters: "caractères",
    incorrectCredentials: "Nom d'utilisateur ou mot de passe incorrect. Veuillez vérifier vos identifiants et réessayer.",
    fillAllFields: "Veuillez remplir tous les champs",
    serverUnavailable: "Impossible de se connecter au serveur. Veuillez vérifier si le backend est en cours d'exécution.",
    currentPasswordIncorrect: "Le mot de passe actuel est incorrect",
    social: "Social",
    searchFriends: "Rechercher des amis",
    activeFriends: "Amis actifs",
    friendsCountUnit: "amis",
    statusOnline: "en ligne",
    statusChatting: "en train de discuter",
    statusInGame: "en jeu",
    statusOffline: "hors ligne",
    status: "Statut",
    chatTitle: "Chat",
    chatDirectMessages: "Messages directs",
    chatSearchFriend: "Rechercher un ami",
    chatUnreadSuffix: "non lus",
    chatNoFriendFound: "Aucun ami trouvé.",
    chatConversation: "Conversation",
    chatSelectFriend: "sélectionnez un ami",
    chatTyping: "En train d'écrire...",
    chatConnected: "Connecté",
    chatReconnecting: "Reconnexion...",
    chatWriteMessage: "Écrire un message...",
    chatSend: "Envoyer",
    chatSelectFriendToWrite: "Selectionnez un ami pour commencer a ecrire.",
    chatPickFriendPrompt: "Choisissez un ami dans la colonne de gauche pour discuter.",
    chatNoMessagesYet: "Pas encore de messages. Dites bonjour.",
    chatSeen: "Vu",
    chatFailedLoadProfile: "Impossible de charger votre profil",
    chatFailedLoadMessages: "Impossible de charger les messages",
    chatFailedLoadFriends: "Impossible de charger les amis",
    chatFailedInitialize: "Impossible d'initialiser le chat",
    chatRealtimeError: "Erreur de chat en temps reel",
    chatRealtimeParseError: "Impossible d'analyser l'evenement temps reel",
    chatRealtimeConnectionError: "Erreur de connexion temps reel",
    chatSelectFriendFirst: "Selectionnez d'abord un ami",
    chatConnectionNotReady: "La connexion temps reel n'est pas prete",
    chatInvalidFriendId: "Identifiant d'ami invalide",
    chatWsMissingToken: "Jeton d'authentification manquant",
    chatWsInvalidToken: "Jeton d'authentification invalide",
    chatWsNotRegistered: "Utilisateur non enregistre",
    chatWsInvalidToUserId: "Destinataire invalide",
    chatWsInvalidWithUserId: "Utilisateur cible invalide",
    chatWsInvalidMessage: "Message invalide",
    chatWsNotFriends: "Vous n'etes pas amis",
    chatWsFailedSaveMessage: "Impossible d'enregistrer le message",
    chatWsUnknownMessageType: "Type de message inconnu",
    chatWsMessageTooLarge: "Message trop volumineux",
    chatWsInvalidJson: "JSON invalide",
    noEloYet: "Pas encore d'ELO",
    avatarAltSuffix: "avatar",
    lastSeen: "Vu",
    inviteToPlay: "Inviter à jouer",
    remove: "Retirer",
    noFriendsMatch: "Aucun ami ne correspond à votre recherche",
    addFriend: "Ajouter un ami",
    usernameOrEmail: "Nom d'utilisateur ou ID",
    sending: "Envoi...",
    sendRequest: "Envoyer une demande",
    messageAction: "Message",
    requests: "Demandes",
    pending: "en attente",
    noPendingRequests: "Aucune demande en attente",
    enterUsernameOrId: "Veuillez saisir un nom d'utilisateur ou un id",
    missingAuthToken: "Jeton d'authentification manquant",
    userNotFound: "Utilisateur introuvable",
    failedSendRequest: "Echec de l'envoi de la demande d'ami",
    requestSent: "Demande d'ami envoyee",
    loadingFriends: "Chargement des amis...",
    unableLoadFriends: "Impossible de charger les amis",
    loading: "Chargement...",
    mutualFriends: "amis en commun",
    accept: "Accepter",
    decline: "Refuser",
    failedAcceptRequest: "Echec de l'acceptation de la demande",
    failedRejectRequest: "Echec du refus de la demande",
    failedRemoveFriend: "Echec de la suppression de l'ami",
    friendRequestAlreadyExists: "Une demande d'ami existe deja",
    alreadyFriends: "Vous etes deja amis",
    cannotAddYourself: "Tu ne peux pas t'ajouter toi-meme",
    friendRequestAcceptedAuto: "Demande d'ami acceptee",
    friendNotFound: "Ami introuvable",
    failedLoadFriendRequests: "Echec du chargement des demandes d'amis",
    failedLoadFriends: "Echec du chargement des amis",
    failedResolveUser: "Impossible de trouver cet utilisateur",
    // Extra Info Page
    aboutThisGame: "À Propos de ce Jeu",
    aboutGameDesc: "Bienvenue sur ft_transcendence, une plateforme moderne de jeu en ligne Pierre Papier Ciseaux. Jouez contre des bots IA ou défiez d'autres joueurs dans des matchs multijoueurs en temps réel.",
    trackScoreDesc: "Suivez votre score, compétitionnez avec des amis et améliorez votre stratégie dans ce jeu classique de chance et de compétence.",
    howToPlay: "Comment Jouer",
    playVsBotsDesc: "Défiez des adversaires IA et testez vos compétences",
    playVsHumansDesc: "Créez ou rejoignez une salle pour jouer avec d'autres joueurs",
    scoreTrackingDesc: "Vos scores persistent tout au long de votre session de jeu",
    multipleRoundsDesc: "Jouez autant de rounds que vous le souhaitez",
    accountSettings: "Paramètres du Compte",
    manageProfileDesc: "Gérez votre profil depuis la page Paramètres:",
    changeUsername: "Changez votre nom d'utilisateur",
    updateEmail: "Mettez à jour votre adresse e-mail",
    updatePassword: "Changez votre mot de passe",
    updateProfilePic: "Mettez à jour votre photo de profil",
    legalPrivacy: "Légal et Confidentialité",
    reviewPoliciesDesc: "Veuillez consulter nos politiques importantes avant d'utiliser l'application:",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions de Service",
    faq: "Questions Fréquemment Posées",
    isDataSecure: "Mes données sont-elles sécurisées?",
    isDataSecureAns: "Oui, nous utilisons le chiffrement standard de l'industrie pour protéger vos données personnelles. Consultez notre Politique de Confidentialité pour plus de détails.",
    canPlayOffline: "Puis-je jouer hors ligne?",
    canPlayOfflineAns: "Ce jeu nécessite une connexion Internet pour jouer, car les scores et les fonctionnalités multijoueurs dépendent du serveur.",
    reportBug: "Comment signaler un bug?",
    reportBugAns: "Si vous rencontrez des problèmes, veuillez contacter le support via les paramètres de votre compte.",
    // Privacy Policy Page
    privacyPageTitle: "Politique de Confidentialité",
    lastUpdated: "Dernière mise à jour:",
    privacyIntro: "ft_transcendence s'engage à protéger votre confidentialité. Cette Politique de Confidentialité explique comment nous collectons, utilisons, divulguons et protégeons vos informations lorsque vous utilisez notre application.",
    privacySection1: "Introduction",
    privacySection2: "Informations que Nous Collectons",
    privacyCollectDesc: "Nous pouvons collecter des informations vous concernant de diverses façons. Les informations que nous pouvons collecter incluent:",
    privacyPersonalData: "Données Personnelles: Nom d'utilisateur, adresse e-mail, mot de passe, photo de profil et préférences de compte.",
    privacyGameData: "Données de Jeu: Scores de jeu, historique des matchs et statistiques de jeu.",
    privacyUsageData: "Données d'Utilisation: Informations sur la façon dont vous interagissez avec l'application, y compris l'adresse IP et les informations de l'appareil.",
    privacyCookies: "Cookies: Nous utilisons des cookies pour améliorer votre expérience utilisateur et suivre vos préférences.",
    privacySection3: "Utilisation de Vos Informations",
    privacyUseDesc: "Avoir des informations exactes vous concernant nous permet de vous fournir une expérience fluide, efficace et personnalisée. Spécifiquement, nous pouvons utiliser les informations collectées à propos de vous pour:",
    privacyUse1: "Créer et gérer votre compte",
    privacyUse2: "Traiter et améliorer votre expérience de jeu",
    privacyUse3: "Suivre vos statistiques et scores de jeu",
    privacyUse4: "Vous envoyer des notifications sur les mises à jour liées au jeu",
    privacyUse5: "Répondre à vos demandes et fournir un support client",
    privacyUse6: "Surveiller et analyser les modèles et tendances d'utilisation",
    privacySection4: "Divulgation de Vos Informations",
    privacyDisclosureDesc: "Nous ne vendons, n'échangeons ni ne louons les informations d'identification personnelle des utilisateurs à d'autres. Nous pouvons divulguer les informations si la loi l'exige ou si nous croyons de bonne foi que cette divulgation est nécessaire pour se conformer aux obligations légales.",
    privacySection5: "Sécurité de Vos Informations",
    privacySecurityDesc: "Nous utilisons des mesures de sécurité administratives, techniques et physiques pour protéger vos informations personnelles. Cependant, aucune méthode de transmission sur Internet ou stockage électronique n'est complètement sécurisée. Bien que nous nous efforcions d'utiliser des moyens commercialement acceptables pour protéger vos informations personnelles, nous ne pouvons pas garantir sa sécurité absolue.",
    privacySection6: "Nous Contacter",
    privacyContactDesc: "Si vous avez des questions sur cette Politique de Confidentialité, veuillez nous contacter via les paramètres de votre compte ou la section support de l'application.",
    privacySection7: "Modifications de cette Politique de Confidentialité",
    privacyChangesDesc: "Nous nous réservons le droit de modifier cette politique de confidentialité à tout moment. Les modifications prendront effet immédiatement après leur publication. Si nous apportons des modifications importantes à cette politique, nous vous en informerons ici.",
    // Terms of Service Page
    termsPageTitle: "Conditions de Service",
    termsSection1: "Accord aux Conditions",
    termsAgreementDesc: "En accédant et en utilisant ft_transcendence, vous acceptez d'être lié par ces Conditions de Service. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser ce service.",
    termsSection2: "Licence d'Utilisation",
    termsLicenseDesc: "La permission vous est accordée de télécharger temporairement une copie des matériaux sur ft_transcendence à des fins de visualisation personnelle et non commerciale. Sous cette licence, vous ne pouvez pas:",
    termsLicense1: "Modifier ou copier les matériaux",
    termsLicense2: "Utiliser les matériaux à des fins commerciales ou pour un affichage public",
    termsLicense3: "Tenter de décompiler ou d'inverser l'ingénierie de tout logiciel contenu dans l'Application",
    termsLicense4: "Supprimer les avis de droits d'auteur ou autres notations propriétaires des matériaux",
    termsLicense5: "Transférer les matériaux à une autre personne ou 'refléter' les matériaux sur un autre serveur",
    termsLicense6: "Violer les lois ou réglementations applicables relatives à l'accès ou à l'utilisation de l'Application",
    termsSection3: "Inscription au Compte",
    termsAccountDesc: "Lorsque vous créez un compte sur ft_transcendence, vous acceptez de fournir des informations exactes, actuelles et complètes. Vous êtes responsable du maintien de la confidentialité de vos informations de compte et de votre mot de passe.",
    termsSection4: "Conduite de l'Utilisateur",
    termsConductDesc: "Vous acceptez de ne pas vous engager dans une conduite qui restreint ou inhibe l'utilisation ou la jouissance de l'Application par une personne, y compris:",
    termsConduct1: "Harcèlement ou cause de détresse ou d'inconfort à toute personne",
    termsConduct2: "Transmission de contenu obscène ou offensant",
    termsConduct3: "Perturbation du flux normal de dialogue dans l'Application",
    termsConduct4: "Tentative d'accès non autorisé à l'Application ou à ses systèmes",
    termsConduct5: "Utilisation d'outils automatisés pour collecter des données de l'Application",
    termsSection5: "Clause de Non-Responsabilité",
    termsWarrantiesDesc: "Les matériaux sur ft_transcendence sont fournis 'tels quels'. ft_transcendence ne donne aucune garantie, expresse ou implicite.",
    termsSection6: "Limitation de Responsabilité",
    termsLiabilityDesc: "En aucun cas ft_transcendence ou ses fournisseurs ne seront responsables de tout dommage découlant de l'utilisation ou de l'impossibilité d'utiliser les matériaux sur ft_transcendence.",
    termsSection7: "Exactitude des Matériaux",
    termsAccuracyDesc: "Les matériaux sur ft_transcendence pourraient contenir des erreurs techniques, typographiques ou photographiques. ft_transcendence ne garantit pas que les matériaux sont exacts, complets ou actuels.",
    termsSection8: "Modifications",
    termsModificationsDesc: "ft_transcendence peut réviser ces conditions de service à tout moment sans avis préalable. En utilisant cette Application, vous acceptez d'être lié par la version actuelle de ces conditions.",
    termsSection9: "Loi Applicable",
    termsGoverningDesc: "Ces termes et conditions sont régis par les lois de la juridiction dans laquelle ft_transcendence opère.",
    termsSection10: "Informations de Contact",
    termsContactDesc: "Si vous avez des questions sur ces Conditions de Service, veuillez nous contacter via la section support de l'application.",
    allRightsReserved: "Tous droits réservés.",
    room: "Salle",
    creatingRoom: "Création de la salle...",
    creatingGame: "Creation de la partie...",
    joiningRoom: "Rejoindre la salle...",
    roomNotFound: "Salle introuvable",
    roomCreatedWaiting: "Salle créée. En attente de l'adversaire...",
    missingRoomCode: "Code de salle manquant",
    connectionNotReady: "Connexion non prête",
    gameFinished: "Partie terminée",
    vs: "VS",
    validate: "Valider"
  },
  es: {
    welcome: "Bienvenido a ft_transcendence",
    content: "El contenido de tu aplicación va aquí.",
    language: "Idioma",
    hello: "Hola",
    extraInfo: "Información extra",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    username: "Nombre de usuario",
    password: "Contraseña",
    email: "Correo electrónico",
    confirmPassword: "Confirmar contraseña",
    friendsList: "Lista de amigos",
    playVsBots: "Jugar vs bots",
    playVsHumans: "Jugar vs humanos",
    playVsPlayers: "Jugador contra jugador",
    logout: "Cerrar sesión",
    profileTitle: "Mi perfil",
    publicProfileTitle: "Perfil publico",
    profileDetails: "Detalles del perfil",
    gamesPlayed: "Partidas jugadas",
    gamesWon: "Partidas ganadas",
    profileText: "Texto del perfil",
    profileTextPlaceholder: "Escribe un texto corto para tu perfil...",
    profileTextEmpty: "Todavia no hay texto de perfil.",
    saveProfileText: "Guardar texto",
    profileTextSaved: "Texto del perfil guardado",
    failedSaveProfileText: "No se pudo guardar el texto del perfil",
    profileActions: "Acciones",
    profileDangerZone: "Zona de peligro",
    deleteAccount: "Eliminar cuenta",
    confirmDeleteAccount: "¿Seguro que quieres eliminar tu cuenta? Esta accion es irreversible.",
    deletingAccount: "Eliminando...",
    failedDeleteAccount: "No se pudo eliminar la cuenta",
    settings: "Configuración",
    change: "Cambiar",
    changeemailaddress: "Cambiar dirección de correo electrónico",
    changeusername: "Cambiar nombre de usuario",
    changeprofilepicture: "Cambiar foto de perfil",
    changepassword: "Cambiar contraseña",
    changeEmail: "Cambiar correo",
    changePassword: "Cambiar contrasena",
    changeProfilePicture: "Cambiar foto de perfil",
    confirmEmail: "Confirmar correo",
    confirmNewEmail: "Confirmar nuevo correo",
    confirmNewPassword: "Confirmar nueva contrasena",
    confirmNewUsername: "Confirmar nuevo nombre de usuario",
    confirmUsername: "Confirmar nombre de usuario",
    currentEmail: "Correo actual",
    currentPassword: "Contrasena actual",
    currentUsername: "Nombre de usuario actual",
    emailsDoNotMatch: "Los correos no coinciden",
    enterCurrentPassword: "Ingresa la contrasena actual",
    enterNewEmail: "Ingresa el nuevo correo",
    enterNewPassword: "Ingresa la nueva contrasena",
    enterNewUsername: "Ingresa el nuevo nombre de usuario",
    fileTooLarge: "Archivo demasiado grande (max 5MB)",
    imageRequirements: "PNG, JPG, WEBP o GIF, hasta 5MB",
    invalidEmail: "Correo invalido",
    invalidFileType: "Tipo de archivo invalido",
    invalidUsername: "Nombre de usuario invalido",
    key: "Clave",
    newEmail: "Nuevo correo",
    newPassword: "Nueva contrasena",
    newUsername: "Nuevo nombre de usuario",
    noFileSelected: "Ningun archivo seleccionado",
    passwordNeedsNumber: "La contrasena debe incluir al menos un numero",
    passwordNeedsUppercase: "La contrasena debe incluir al menos una mayuscula",
    passwordRequirements: "Al menos 8 caracteres, una mayuscula y un numero",
    passwordTooShort: "Contrasena demasiado corta",
    passwordsDoNotMatch: "Las contrasenas no coinciden",
    sameEmail: "El nuevo correo debe ser diferente",
    samePassword: "La nueva contrasena debe ser diferente",
    sameUsername: "El nuevo nombre de usuario debe ser diferente",
    selectImage: "Seleccionar imagen",
    userExists: "El usuario ya existe",
    usernamesDoNotMatch: "Los nombres de usuario no coinciden",
    yourKey: "Tu clave",
    profilePicture: "Foto de perfil",
    rock: "piedra",
    paper: "papel",
    scissors: "tijeras",
    selected: "Seleccionado",
    botChoice: "Elección del bot",
    opponentChoice: "Elección del oponente",
    yourChoice: "Tu elección",
    playAgain: "Jugar de nuevo",
    scoreTrackingComingSoon: "Seguimiento de puntuación próximamente...",
    you: "Tú",
    bot: "Bot",
    opponent: "Oponente",
    rockPaperScissors: "Piedra Papel Tijeras",
    createRoom: "Crear una sala",
    joinRoom: "Unirse a una sala",
    makeYourChoice: "Haz tu elección",
    enterRoomName: "Ingresa un nombre de sala",
    roomNamePlaceholder: "Mi Sala",
    characters: "caracteres",
    incorrectCredentials: "Nombre de usuario o contraseña incorrectos. Por favor, verifica tus credenciales e inténtalo de nuevo.",
    fillAllFields: "Por favor, rellena todos los campos",
    serverUnavailable: "No se puede conectar al servidor. Por favor, verifica si el backend está en ejecución.",
    currentPasswordIncorrect: "La contraseña actual es incorrecta",
    social: "Social",
    searchFriends: "Buscar amigos",
    activeFriends: "Amigos activos",
    friendsCountUnit: "amigos",
    statusOnline: "en linea",
    statusChatting: "chateando",
    statusInGame: "en partida",
    statusOffline: "desconectado",
    status: "Estado",
    chatTitle: "Chat",
    chatDirectMessages: "Mensajes directos",
    chatSearchFriend: "Buscar un amigo",
    chatUnreadSuffix: "sin leer",
    chatNoFriendFound: "No se encontro ningun amigo.",
    chatConversation: "Conversacion",
    chatSelectFriend: "Selecciona un amigo",
    chatTyping: "Escribiendo...",
    chatConnected: "Conectado",
    chatReconnecting: "Reconectando",
    chatWriteMessage: "Escribe un mensaje...",
    chatSend: "Enviar",
    chatSelectFriendToWrite: "Selecciona un amigo para comenzar a escribir mensajes.",
    chatPickFriendPrompt: "Selecciona un amigo en la columna izquierda para empezar a chatear.",
    chatNoMessagesYet: "Todavia no hay mensajes. Saluda.",
    chatSeen: "Visto",
    chatFailedLoadProfile: "No se pudo cargar tu perfil",
    chatFailedLoadMessages: "No se pudieron cargar los mensajes",
    chatFailedLoadFriends: "No se pudieron cargar los amigos",
    chatFailedInitialize: "No se pudo inicializar el chat",
    chatRealtimeError: "Error de chat en tiempo real",
    chatRealtimeParseError: "No se pudo analizar el evento en tiempo real",
    chatRealtimeConnectionError: "Error de conexion en tiempo real",
    chatSelectFriendFirst: "Selecciona primero un amigo",
    chatConnectionNotReady: "La conexion en tiempo real no esta lista",
    chatInvalidFriendId: "Identificador de amigo invalido",
    chatWsMissingToken: "Falta el token de autenticacion",
    chatWsInvalidToken: "Token de autenticacion invalido",
    chatWsNotRegistered: "No registrado",
    chatWsInvalidToUserId: "Destinatario invalido",
    chatWsInvalidWithUserId: "Usuario objetivo invalido",
    chatWsInvalidMessage: "Mensaje invalido",
    chatWsNotFriends: "No son amigos",
    chatWsFailedSaveMessage: "No se pudo guardar el mensaje",
    chatWsUnknownMessageType: "Tipo de mensaje desconocido",
    chatWsMessageTooLarge: "Mensaje demasiado grande",
    chatWsInvalidJson: "JSON invalido",
    noEloYet: "Aun sin ELO",
    avatarAltSuffix: "avatar",
    lastSeen: "Ultima vez visto",
    inviteToPlay: "Invitar a jugar",
    remove: "Eliminar",
    noFriendsMatch: "Ningun amigo coincide con tu busqueda",
    addFriend: "Agregar amigo",
    usernameOrEmail: "Nombre de usuario o ID",
    sending: "Enviando...",
    sendRequest: "Enviar solicitud",
    messageAction: "Mensaje",
    requests: "Solicitudes",
    pending: "pendientes",
    noPendingRequests: "No hay solicitudes pendientes",
    enterUsernameOrId: "Ingresa un nombre de usuario o id",
    missingAuthToken: "Falta el token de autenticacion",
    userNotFound: "Usuario no encontrado",
    failedSendRequest: "No se pudo enviar la solicitud de amistad",
    requestSent: "Solicitud de amistad enviada",
    loadingFriends: "Cargando amigos...",
    unableLoadFriends: "No se pudieron cargar los amigos",
    loading: "Cargando...",
    mutualFriends: "amigos en comun",
    accept: "Aceptar",
    decline: "Rechazar",
    failedAcceptRequest: "No se pudo aceptar la solicitud",
    failedRejectRequest: "No se pudo rechazar la solicitud",
    failedRemoveFriend: "No se pudo eliminar al amigo",
    friendRequestAlreadyExists: "La solicitud de amistad ya existe",
    alreadyFriends: "Ya son amigos",
    cannotAddYourself: "No puedes agregarte a ti mismo",
    friendRequestAcceptedAuto: "Solicitud de amistad aceptada",
    friendNotFound: "Amigo no encontrado",
    failedLoadFriendRequests: "No se pudieron cargar las solicitudes de amistad",
    failedLoadFriends: "No se pudieron cargar los amigos",
    failedResolveUser: "No se pudo encontrar este usuario",
    // Extra Info Page
    aboutThisGame: "Acerca de este Juego",
    aboutGameDesc: "Bienvenido a ft_transcendence, una plataforma moderna de juego en línea de Piedra Papel Tijeras. Juega contra adversarios IA o desafía a otros jugadores en partidas multijugador en tiempo real.",
    trackScoreDesc: "Sigue tu puntuación, compite con amigos y mejora tu estrategia en este juego clásico de azar y habilidad.",
    howToPlay: "Cómo Jugar",
    playVsBotsDesc: "Desafía a adversarios IA y prueba tus habilidades",
    playVsHumansDesc: "Crea o únete a una sala para jugar con otros jugadores",
    scoreTrackingDesc: "Tus puntuaciones persisten durante tu sesión de juego",
    multipleRoundsDesc: "Juega tantas rondas como quieras",
    accountSettings: "Configuración de Cuenta",
    manageProfileDesc: "Gestiona tu perfil desde la página de Configuración:",
    changeUsername: "Cambia tu nombre de usuario",
    updateEmail: "Actualiza tu dirección de correo electrónico",
    updatePassword: "Cambia tu contraseña",
    updateProfilePic: "Actualiza tu foto de perfil",
    legalPrivacy: "Legal y Privacidad",
    reviewPoliciesDesc: "Por favor, revisa nuestras políticas importantes antes de usar la aplicación:",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    faq: "Preguntas Frecuentes",
    isDataSecure: "¿Son mis datos seguros?",
    isDataSecureAns: "Sí, utilizamos encriptación estándar de la industria para proteger tus datos personales. Consulta nuestra Política de Privacidad para más información.",
    canPlayOffline: "¿Puedo jugar sin conexión?",
    canPlayOfflineAns: "Este juego requiere una conexión a Internet para jugar, ya que las puntuaciones y las funciones multijugador dependen del servidor.",
    reportBug: "¿Cómo reporto un error?",
    reportBugAns: "Si encuentras algún problema, por favor contacta con soporte a través de la configuración de tu cuenta.",
    // Privacy Policy Page
    privacyPageTitle: "Política de Privacidad",
    lastUpdated: "Última actualización:",
    privacyIntro: "ft_transcendence se compromete a proteger tu privacidad. Esta Política de Privacidad explica cómo recopilamos, utilizamos, divulgamos y protegemos tu información cuando usas nuestra aplicación.",
    privacySection1: "Introducción",
    privacySection2: "Información que Recopilamos",
    privacyCollectDesc: "Podemos recopilar información sobre ti de varias formas. La información que podemos recopilar incluye:",
    privacyPersonalData: "Datos Personales: Nombre de usuario, dirección de correo electrónico, contraseña, foto de perfil y preferencias de cuenta.",
    privacyGameData: "Datos de Juego: Puntuaciones de juego, historial de partidas y estadísticas de juego.",
    privacyUsageData: "Datos de Uso: Información sobre cómo interactúas con la aplicación, incluyendo dirección IP e información del dispositivo.",
    privacyCookies: "Cookies: Utilizamos cookies para mejorar tu experiencia de usuario y rastrear tus preferencias.",
    privacySection3: "Uso de tu Información",
    privacyUseDesc: "Tener información precisa sobre ti nos permite proporcionarte una experiencia fluida, eficiente y personalizada. Específicamente, podemos utilizar la información recopilada sobre ti para:",
    privacyUse1: "Crear y gestionar tu cuenta",
    privacyUse2: "Procesar y mejorar tu experiencia de juego",
    privacyUse3: "Rastrear tus estadísticas y puntuaciones de juego",
    privacyUse4: "Enviarte notificaciones sobre actualizaciones relacionadas con el juego",
    privacyUse5: "Responder a tus consultas y proporcionar soporte al cliente",
    privacyUse6: "Monitorear y analizar patrones y tendencias de uso",
    privacySection4: "Divulgación de tu Información",
    privacyDisclosureDesc: "No vendemos, no intercambiamos ni alquilamos la información de identificación personal de los usuarios a terceros. Podemos divulgar información cuando lo requiera la ley o de buena fe cuando sea necesario cumplir con obligaciones legales.",
    privacySection5: "Seguridad de tu Información",
    privacySecurityDesc: "Utilizamos medidas de seguridad administrativas, técnicas y físicas para proteger tu información personal. Sin embargo, ningún método de transmisión por Internet o almacenamiento electrónico es completamente seguro. Aunque nos esforzamos por utilizar medios comercialmente aceptables, no podemos garantizar la seguridad absoluta.",
    privacySection6: "Contáctanos",
    privacyContactDesc: "Si tienes preguntas sobre esta Política de Privacidad, contáctanos a través de la configuración de tu cuenta o la sección de soporte de la aplicación.",
    privacySection7: "Cambios en esta Política de Privacidad",
    privacyChangesDesc: "Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento. Los cambios tendrán efecto inmediatamente después de su publicación. Si realizamos cambios importantes, te lo notificaremos aquí.",
    // Terms of Service Page
    termsPageTitle: "Términos de Servicio",
    termsSection1: "Acuerdo con los Términos",
    termsAgreementDesc: "Al acceder y utilizar ft_transcendence, aceptas estar vinculado por estos Términos de Servicio. Si no aceptas estos términos, no uses este servicio.",
    termsSection2: "Licencia de Uso",
    termsLicenseDesc: "Se te otorga permiso para descargar temporalmente una copia de los materiales en ft_transcendence para visualización personal no comercial. Bajo esta licencia no puedes:",
    termsLicense1: "Modificar o copiar los materiales",
    termsLicense2: "Usar los materiales para fines comerciales o para visualización pública",
    termsLicense3: "Intentar descompilar o aplicar ingeniería inversa a cualquier software contenido en la Aplicación",
    termsLicense4: "Eliminar notificaciones de derechos de autor u otras notaciones de propiedad de los materiales",
    termsLicense5: "Transferir los materiales a otra persona o 'reflejar' los materiales en otro servidor",
    termsLicense6: "Violar leyes o regulaciones aplicables relacionadas con el acceso o uso de la Aplicación",
    termsSection3: "Registro de Cuenta",
    termsAccountDesc: "Cuando creas una cuenta en ft_transcendence, aceptas proporcionar información precisa, actual y completa. Eres responsable de mantener la confidencialidad de la información de tu cuenta y tu contraseña.",
    termsSection4: "Conducta del Usuario",
    termsConductDesc: "Aceptas no realizar ninguna conducta que restrinja o inhiba el uso o disfrute de la Aplicación por parte de cualquier persona, incluyendo:",
    termsConduct1: "Acosar o causar angustia a cualquier persona",
    termsConduct2: "Transmitir contenido obsceno u ofensivo",
    termsConduct3: "Interrumpir el flujo normal de diálogo dentro de la Aplicación",
    termsConduct4: "Intentar obtener acceso no autorizado a la Aplicación o sus sistemas",
    termsConduct5: "Usar herramientas automatizadas para recopilar datos de la Aplicación",
    termsSection5: "Exención de Garantías",
    termsWarrantiesDesc: "Los materiales en ft_transcendence se proporcionan 'tal cual'. ft_transcendence no otorga garantías, expresas o implícitas.",
    termsSection6: "Limitación de Responsabilidad",
    termsLiabilityDesc: "En ningún caso ft_transcendence o sus proveedores serán responsables de los daños derivados del uso o la imposibilidad de usar los materiales.",
    termsSection7: "Exactitud de los Materiales",
    termsAccuracyDesc: "Los materiales en ft_transcendence podrían contener errores técnicos, tipográficos o fotográficos. ft_transcendence no garantiza que los materiales sean precisos, completos o actuales.",
    termsSection8: "Modificaciones",
    termsModificationsDesc: "ft_transcendence puede revisar estos términos de servicio en cualquier momento sin aviso previo. Al usar esta Aplicación, aceptas estar vinculado por la versión actual de estos términos.",
    termsSection9: "Ley Aplicable",
    termsGoverningDesc: "Estos términos se rigen por las leyes de la jurisdicción en la que opera ft_transcendence.",
    termsSection10: "Información de Contacto",
    termsContactDesc: "Si tienes preguntas sobre estos Términos de Servicio, contáctanos a través de la sección de soporte de la aplicación.",
    allRightsReserved: "Todos los derechos reservados.",
    room: "Sala",
    creatingRoom: "Creando sala...",
    creatingGame: "Creando partida...",
    joiningRoom: "Uniéndose a la sala...",
    roomNotFound: "Sala no encontrada",
    roomCreatedWaiting: "Sala creada. Esperando al oponente...",
    missingRoomCode: "Código de sala faltante",
    connectionNotReady: "Conexión no lista",
    gameFinished: "Juego terminado",
    vs: "VS",
    validate: "Validar"
  },
};

// Create the language context with undefined as initial value
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
const LANGUAGE_STORAGE_KEY = "language";
const LANGUAGE_CHANGED_EVENT = "language-changed";

function parseLanguage(value: string | null): Language | null {
  if (value === "en" || value === "fr" || value === "es") {
    return value;
  }
  return null;
}

function browserLanguage(): Language {
  if (typeof window === "undefined") return "en";
  const value = window.navigator.language.toLowerCase();
  if (value.startsWith("fr")) return "fr";
  if (value.startsWith("es")) return "es";
  return "en";
}

function getLanguageSnapshot(): Language {
  if (typeof window === "undefined") return "en";
  try {
    const saved = parseLanguage(window.localStorage.getItem(LANGUAGE_STORAGE_KEY));
    if (saved) return saved;
  } catch {}
  return browserLanguage();
}

function subscribeLanguage(callback: () => void) {
  if (typeof window === "undefined") {
    return () => {};
  }
  const onStorage = (event: StorageEvent) => {
    if (event.key === null || event.key === LANGUAGE_STORAGE_KEY) {
      callback();
    }
  };
  const onLanguageChanged = () => callback();
  window.addEventListener("storage", onStorage);
  window.addEventListener(LANGUAGE_CHANGED_EVENT, onLanguageChanged);
  return () => {
    window.removeEventListener("storage", onStorage);
    window.removeEventListener(LANGUAGE_CHANGED_EVENT, onLanguageChanged);
  };
}

/**
 * LanguageProvider Component
 * 
 * Wraps the application and provides language context to all child components.
 * Should be placed high in the component tree (typically in layout.tsx).
 */
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const language = useSyncExternalStore<Language>(
    subscribeLanguage,
    getLanguageSnapshot,
    () => "en" as Language
  );

  /**
   * Toggle between English, French, and Spanish
   * Updates state and persists preference to localStorage
   */
  const toggleLanguage = () => {
    if (typeof window === "undefined") return;
    const languageCycle: Record<Language, Language> = { en: "fr", fr: "es", es: "en" };
    const newLanguage = languageCycle[language];
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage);
    } catch {}
    window.dispatchEvent(new Event(LANGUAGE_CHANGED_EVENT));
  };

  /**
   * Translation function
   * @param key - The translation key to look up
   * @returns The translated string in the current language, or the key itself if not found
   */
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  // Provide language state and functions to all children
  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

/**
 * Custom hook to access language context
 * 
 * @throws Error if used outside of LanguageProvider
 * @returns Language context containing current language, toggle function, and translation function
 * 
 * Usage:
 *   const { language, toggleLanguage, t } = useLanguage();
 *   <h1>{t("welcome")}</h1>
 */
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
